In [1]:
import pandas as pd

In [2]:
crime = pd.read_csv('data/crime_district.csv')
amenities = pd.read_csv('data/hh_access_amenities.csv')
income = pd.read_csv('data/hh_income_district.csv')
inequality = pd.read_csv('data/hh_inequality_district.csv')
poverty = pd.read_csv('data/hh_poverty_district.csv')
pop_dist = pd.read_csv('data/population_district.csv')
schools_dist = pd.read_csv('data/schools_district.csv')
enrolment = pd.read_csv('data/enrolment_school_district.csv')

In [3]:
dfs = {
    'income': income, 'poverty': poverty, 'inequality': inequality,
    'amenities': amenities, 'population': pop_dist, 'crime': crime,
    'schools': schools_dist, 'enrolment': enrolment,
}

In [4]:
# states = ['Johor', 'Kedah', 'Kelantan', 'Malaysia',
#           'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis',
#           'Pulau Pinang', 'Sabah', 'Sarawak', 'Selangor',
#           'Terengganu', 'W.P. Kuala Lumpur', 'W.P. Labuan', 'W.P. Putrajaya'], states names are obtained from previous EDA not recorded in this notebook

In [5]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Johor']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Batu Pahat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Johor Bahru,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kluang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Tinggi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kulai,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Mersing,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Muar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pontian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Segamat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tangkak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Iskandar Puteri,,,,,,2016-2023,,
Johor Bahru Selatan,,,,,,2016-2023,,
Johor Bahru Utara,,,,,,2016-2023,,
Kulaijaya,,,,,,2016-2023,,
Ledang,,,,,,2016-2023,,
Nusajaya,,,,,,2016-2023,,
Seri Alam,,,,,,2016-2023,,
Pasir Gudang,,,,,,,,2023-2025

In [6]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kedah']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Baling,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bandar Baharu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2020-2023,2017-2025,2017-2022
Kota Setar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Muda,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kubang Pasu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kulim,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Langkawi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Padang Terap,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pendang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pokok Sena,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Sik,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Yan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Bandar Bharu,,,,,,2016-2019,,
Kuala Muda/Yan,,,,,,,,2023-2024
Kulim/Bandar Baharu,,,,,,,,2023-2025

In [7]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kedah']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Baling,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bandar Baharu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2020-2023,2017-2025,2017-2022
Kota Setar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Muda,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kubang Pasu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kulim,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Langkawi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Padang Terap,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pendang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pokok Sena,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Sik,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Yan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Bandar Bharu,,,,,,2016-2019,,
Kuala Muda/Yan,,,,,,,,2023-2024
Kulim/Bandar Baharu,,,,,,,,2023-2025

In [8]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kelantan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bachok,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Gua Musang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Jeli,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kecil Lojing,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Kota Bharu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Krai,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Machang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pasir Mas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pasir Puteh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Tanah Merah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tumpat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Pasir Putih,,,,,,,,2023-2025

In [9]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Melaka']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Alor Gajah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Jasin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Melaka Tengah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [10]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Negeri Sembilan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Jelebu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Jempol,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2018-2022
Kuala Pilah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Port Dickson,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Rembau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Seremban,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tampin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Nilai,,,,,,2016-2023,,
Jempol/Jelebu,,,,,,,,2023-2025

In [11]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Pahang']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bentong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bera,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Cameron Highlands,2019-2024,2019-2024,2019-2024,2016-2024,2020-2021,2020-2023,2017-2025,2017-2025
Jerantut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuantan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lipis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2022,2017-2025
Maran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pekan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Raub,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Rompin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Temerloh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
Cameron Highland,,,,,2022-2025,2016-2019,,
All,,,,,,2016-2023,,
Kuala Lipis,,,,,,2016-2023,2017-2025,2018-2022

In [12]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Perak']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bagan Datuk,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Batang Padang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Hilir Perak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Hulu Perak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kampar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2018-2022
Kerian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kinta,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Kuala Kangsar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Larut & Matang,2024-2024,2024-2024,2024-2024,,,,,
Larut dan Matang,2019-2022,2019-2022,2019-2022,2016-2024,,,2017-2022,2017-2017
Manjung,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,,2023-2025
Muallim,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2025
Perak Tengah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Selama,2022-2024,2022-2024,2022-2024,2016-2024,2020-2025,2016-2023,,
All Districts,,,,2016-2024,,,2017-2025,2017-2025
Larut Dan Matang,,,,,2020-2025,,,
All,,,,,,2016-2023,,
Batu Gajah,,,,,,2016-2023,,
Gerik,,,,,,2016-2023,,
Ipoh,,,,,,2016-2023,,
Pengkalan Hulu,,,,,,2016-2023,,
Sungai Siput,,,,,,2016-2023,,
Taiping,,,,,,2016-2023,,
Tanjong Malim,,,,,,2016-2023,,
Tapah,,,,,,2016-2023,,
Larut Matang & Selama,,,,,,,2017-2025,2018-2022
Manjung (Dinding),,,,,,,2017-2025,2017-2022
Kinta Selatan,,,,,,,,2023-2025
Kinta Utara,,,,,,,,2023-2025
Larut/Matang/Selama,,,,,,,,2023-2025

In [13]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Perlis']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Perlis,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,,2017-2025,2017-2022
All,,,,,,2016-2023,,
Arau,,,,,,2016-2023,,
Kangar,,,,,,2016-2023,,
Padang Besar,,,,,,2016-2023,,
All Districts,,,,,,,2017-2025,2017-2025
Jpn Perlis,,,,,,,,2023-2025

In [14]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Pulau Pinang']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Barat Daya,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
S.P. Selatan,2024-2024,2024-2024,2024-2024,,,,,
S.P.Tengah,2024-2024,2024-2024,2024-2024,,,,,
S.P.Utara,2024-2024,2024-2024,2024-2024,,,,,
Seberang Perai Selatan,2019-2022,2019-2022,2019-2022,2016-2024,2020-2023,2016-2023,2017-2025,2017-2025
Seberang Perai Tengah,2019-2022,2019-2022,2019-2022,2016-2024,2020-2023,2016-2023,2017-2025,2017-2025
Seberang Perai Utara,2019-2022,2019-2022,2019-2022,2016-2024,2020-2023,2016-2023,2017-2025,2017-2025
Timur Laut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
Sp Selatan,,,,,2022-2025,,,
Sp Tengah,,,,,2022-2025,,,
Sp Utara,,,,,2022-2025,,,
All,,,,,,2016-2023,,

In [15]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Sabah']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Beaufort,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Beluran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kalabakan,2022-2024,2022-2024,2022-2024,2016-2024,2020-2025,,,
Keningau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kinabatangan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kota Belud,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Kinabalu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Marudu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Penyu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kudat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kunak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lahad Datu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Membakut,2024-2024,2024-2024,2024-2024,,,,,
Nabawan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Papar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Penampang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pitas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Putatan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Ranau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sandakan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Semporna,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sipitang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tambunan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Tawau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Telupid,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Tenom,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tongod,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Tuaran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Kota Kinabatangan,,,,,,2016-2023,,
W.P. Labuan,,,,,,2016-2023,,
Pensiangan,,,,,,,,2023-2025
Telupid/Tongod,,,,,,,,2023-2025

In [16]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Sarawak']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Asajaya,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Bau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Belaga,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Beluru,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Betong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bintulu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bukit Mabong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Dalat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Daro,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Gedong,2024-2024,2024-2024,2024-2024,,,,,
Julau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kabong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Kanowit,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kapit,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuching,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lawas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Limbang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lingga,2024-2024,2024-2024,2024-2024,,,,,
Lubok Antu,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lubok antu,2024-2024,2024-2024,2024-2024,,,,,
Lundu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Maradong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Marudi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Matu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Miri,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Mukah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pakan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Pantu,2024-2024,2024-2024,2024-2024,,,,,
Pusa,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Samarahan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Saratok,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sarikei,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sebauh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Sebuyau,2024-2024,2024-2024,2024-2024,,,,,
Selangau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2022,2017-2025
Serian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sibu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Siburan,2024-2024,2024-2024,2024-2024,,,,,
Simunjan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Song,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sri Aman,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Subis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Tanjung Manis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Tatau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Tebedu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Telang Usan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Kota Samarahan,,,,,,2016-2023,,
Matu Daro,,,,,,2016-2023,,
Meradong,,,,,,2016-2023,,2023-2025
Padawan,,,,,,2016-2023,,2023-2025
Baram,,,,,,,,2023-2025
Tatau/Sebauh,,,,,,,,2023-2025

In [17]:

cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Selangor']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Gombak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Klang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kuala Langat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Selangor,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Petaling,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Sabak Bernam,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sepang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Ulu Langat,2019-2024,2019-2024,2019-2024,,2020-2025,,2017-2025,2017-2025
Ulu Selangor,2019-2024,2019-2024,2019-2024,,2020-2025,,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
Hulu Langat,,,,2016-2024,,,,
Hulu Selangor,,,,2016-2024,,2016-2023,,
All,,,,,,2016-2023,,
Ampang Jaya,,,,,,2016-2023,,
Kajang,,,,,,2016-2023,,
Klang Selatan,,,,,,2016-2023,,
Klang Utara,,,,,,2016-2023,,
Petaling Jaya,,,,,,2016-2023,,
Serdang,,,,,,2016-2023,,
Sg. Buloh,,,,,,2016-2020,,
Shah Alam,,,,,,2016-2023,,
Subang Jaya,,,,,,2016-2023,,
Sungai Buloh,,,,,,2021-2023,,
Petaling Perdana,,,,,,,,2023-2025
Petaling Utama,,,,,,,,2023-2025

In [18]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Terengganu']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Besut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Dungun,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Hulu,2024-2024,2024-2024,2024-2024,,,,,
Hulu Terengganu,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kemaman,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Nerus,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kuala Terengganu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Marang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Setiu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [19]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['W.P. Kuala Lumpur']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
W.P. Kuala Lumpur,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Brickfields,,,,,,2016-2023,,
Cheras,,,,,,2016-2023,,
Dang Wangi,,,,,,2016-2023,,
Sentul,,,,,,2016-2023,,
W.P. Putrajaya,,,,,,2016-2023,,
Wangsa Maju,,,,,,2016-2023,,
All Districts,,,,,,,2017-2025,2017-2025

In [20]:

cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['W.P. Labuan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
W.P. Labuan,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,,2017-2025,2017-2025
All Districts,,,,,,,2017-2025,2017-2025

In [21]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['W.P. Putrajaya']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
W.P. Putrajaya,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,,2017-2025,2017-2025
All Districts,,,,,,,2017-2025,2017-2025

In [22]:
for name, df in dfs.items():
    print({name.upper()})
    print("--- INFO ---")
    df.info()
    print("\n")
    print("="*50 + "\n")

{'INCOME'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          480 non-null    object
 1   district       480 non-null    object
 2   date           480 non-null    object
 3   income_mean    480 non-null    int64
 4   income_median  480 non-null    int64
dtypes: int64(2), object(3)
memory usage: 18.9+ KB


==================================================

{'POVERTY'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             480 non-null    object
 1   district          480 non-null    object
 2   date              480 non-null    object
 3   poverty_absolute  480 non-null    float64
 4   poverty_relative  480 non-null    float64
dtypes: float64(2), object(3)
memory usage: 18.9+ KB


==================================================

{'INEQUALITY'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     480 non-null    object
 1   district  480 non-null    object
 2   date      480 non-null    object
 3   gini      480 non-null    float64
dtypes: float64(1), object(3)
memory usage: 15.1+ KB


==================================================

{'AMENITIES'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         688 non-null    object
 1   state        688 non-null    object
 2   district     688 non-null    object
 3   piped_water  659 non-null    float64
 4   sanitation   658 non-null    float64
 5   electricity  672 non-null    float64
dtypes: float64(3), object(3)
memory usage: 32.4+ KB


==================================================

{'POPULATION'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383040 entries, 0 to 383039
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   state       383040 non-null  object
 1   district    383040 non-null  object
 2   date        383040 non-null  object
 3   sex         383040 non-null  object
 4   age         383040 non-null  object
 5   ethnicity   383040 non-null  object
 6   population  383040 non-null  float64
dtypes: float64(1), object(6)
memory usage: 20.5+ MB


==================================================

{'CRIME'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19152 entries, 0 to 19151
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     19152 non-null  object
 1   district  19152 non-null  object
 2   category  19152 non-null  object
 3   type      19152 non-null  object
 4   date      19152 non-null  object
 5   crimes    19152 non-null  int64
dtypes: int64(1), object(5)
memory usage: 897.9+ KB


==================================================

{'SCHOOLS'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3977 entries, 0 to 3976
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     3977 non-null   object
 1   district  3977 non-null   object
 2   stage     3977 non-null   object
 3   type      3977 non-null   object
 4   date      3977 non-null   object
 5   schools   3977 non-null   int64
dtypes: int64(1), object(5)
memory usage: 186.6+ KB


==================================================

{'ENROLMENT'}
--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12756 entries, 0 to 12755
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     12756 non-null  object
 1   district  12756 non-null  object
 2   stage     12756 non-null  object
 3   sex       12756 non-null  object
 4   date      12756 non-null  object
 5   students  12756 non-null  int64
dtypes: int64(1), object(5)
memory usage: 598.1+ KB


==================================================

### From initial EDA we have found out that the districts are not consistent across datasets. Crime datasets refer to the IPD (Ibu Pejabat Polis Daerah) districts, education datasets refer to PPD (Pejabat Pendidikan Daerah) districts, while the rest refers to state territory districts. There are also aggregate districts included in the datasets, which sums the total stats for every district in the state. Spelling errors, inconsistent naming are also present. Federal territory names are simplified, districts are respelled and combined according to their geographical districts, and in some districts, combined according to their PPD districts to ensure data availability across columns. For the crime dataset, Putrajaya is included as one of Kuala Lumpur's districts, so we have to elevate the crime statistic to Putrajaya state

In [89]:
# 1. Define Federal Territory Renames
wp_renames = {
    "W.P. Kuala Lumpur": "Kuala Lumpur",
    "W.P. Labuan": "Labuan",
    "W.P. Putrajaya": "Putrajaya"
}

# 2. Define Strategy 2 Mapping Dictionaries (Updated for stripped W.P. names)
safe_renames = {
    "Kulaijaya": "Kulai", "Ledang": "Tangkak", "Bandar Bharu": "Bandar Baharu",
    "Pasir Putih": "Pasir Puteh", "Cameron Highland": "Cameron Highlands",
    "Kuala Lipis": "Lipis", "Larut & Matang": "Larut dan Matang",
    "Larut Dan Matang": "Larut dan Matang","Larut Matang & Selama" : "Larut/Matang/Selama",
    "Manjung (Dinding)": "Manjung", "Jpn Perlis": "Perlis",
    "S.P. Selatan": "Seberang Perai Selatan", "Sp Selatan": "Seberang Perai Selatan",
    "S.P.Tengah": "Seberang Perai Tengah", "Sp Tengah": "Seberang Perai Tengah",
    "S.P.Utara": "Seberang Perai Utara", "Sp Utara": "Seberang Perai Utara",
    "Kota Kinabatangan": "Kinabatangan", "Pensiangan": "Nabawan",
    "Kota Samarahan": "Samarahan", "Lubok antu": "Lubok Antu", "Meradong": "Maradong",
    "Hulu Langat": "Ulu Langat", "Hulu Selangor": "Ulu Selangor", "Sg. Buloh": "Sungai Buloh",
    "Hulu": "Hulu Terengganu"
}

sub_districts_to_parents = {
    "Johor Bahru Selatan": "Johor Bahru", "Johor Bahru Utara": "Johor Bahru",
    "Iskandar Puteri": "Johor Bahru", "Nusajaya": "Johor Bahru",
    "Seri Alam": "Johor Bahru", "Pasir Gudang": "Johor Bahru",
    "Nilai": "Seremban", "Ipoh": "Kinta", "Batu Gajah": "Kinta",
    "Kinta Selatan": "Kinta", "Kinta Utara": "Kinta", "Sungai Siput": "Kuala Kangsar",
    "Gerik": "Hulu Perak", "Pengkalan Hulu": "Hulu Perak", "Tapah": "Batang Padang",
    "Tanjong Malim": "Muallim", "Taiping": "Larut dan Matang",
    "Arau": "Perlis", "Kangar": "Perlis", "Padang Besar": "Perlis",
    "Ampang Jaya": "Ulu Langat", "Kajang": "Ulu Langat", "Klang Selatan": "Klang",
    "Klang Utara": "Klang", "Petaling Jaya": "Petaling", "Subang Jaya": "Petaling",
    "Shah Alam": "Petaling", "Sungai Buloh": "Petaling", "Petaling Perdana": "Petaling",
    "Petaling Utama": "Petaling", "Brickfields": "Kuala Lumpur",
    "Cheras": "Kuala Lumpur", "Dang Wangi": "Kuala Lumpur",
    "Sentul": "Kuala Lumpur", "Wangsa Maju": "Kuala Lumpur"
}

fine_to_combined = {
    "Kuala Muda": "Kuala Muda/Yan", "Yan": "Kuala Muda/Yan",
    "Kulim": "Kulim/Bandar Baharu", "Bandar Baharu": "Kulim/Bandar Baharu",
    "Jempol": "Jempol/Jelebu", "Jelebu": "Jempol/Jelebu",
    "Larut dan Matang": "Larut/Matang/Selama", "Selama": "Larut/Matang/Selama",
    "Telupid": "Telupid/Tongod", "Tongod": "Telupid/Tongod",
    "Tatau": "Tatau/Sebauh", "Sebauh": "Tatau/Sebauh",
    "Matu": "Matu/Daro", "Daro": "Matu/Daro"," Matu Daro": "Matu/Daro"
}

# Combine maps
master_map = {**safe_renames, **sub_districts_to_parents, **fine_to_combined, **wp_renames}

print(master_map)

{'Kulaijaya': 'Kulai', 'Ledang': 'Tangkak', 'Bandar Bharu': 'Bandar Baharu', 'Pasir Putih': 'Pasir Puteh', 'Cameron Highland': 'Cameron Highlands', 'Kuala Lipis': 'Lipis', 'Larut & Matang': 'Larut dan Matang', 'Larut Dan Matang': 'Larut dan Matang', 'Larut Matang & Selama': 'Larut/Matang/Selama', 'Manjung (Dinding)': 'Manjung', 'Jpn Perlis': 'Perlis', 'S.P. Selatan': 'Seberang Perai Selatan', 'Sp Selatan': 'Seberang Perai Selatan', 'S.P.Tengah': 'Seberang Perai Tengah', 'Sp Tengah': 'Seberang Perai Tengah', 'S.P.Utara': 'Seberang Perai Utara', 'Sp Utara': 'Seberang Perai Utara', 'Kota Kinabatangan': 'Kinabatangan', 'Pensiangan': 'Nabawan', 'Kota Samarahan': 'Samarahan', 'Lubok antu': 'Lubok Antu', 'Meradong': 'Maradong', 'Hulu Langat': 'Ulu Langat', 'Hulu Selangor': 'Ulu Selangor', 'Sg. Buloh': 'Sungai Buloh', 'Hulu': 'Hulu Terengganu', 'Johor Bahru Selatan': 'Johor Bahru', 'Johor Bahru Utara': 'Johor Bahru', 'Iskandar Puteri': 'Johor Bahru', 'Nusajaya': 'Johor Bahru', 'Seri Alam': 'Johor Bahru', 'Pasir Gudang': 'Johor Bahru', 'Nilai': 'Seremban', 'Ipoh': 'Kinta', 'Batu Gajah': 'Kinta', 'Kinta Selatan': 'Kinta', 'Kinta Utara': 'Kinta', 'Sungai Siput': 'Kuala Kangsar', 'Gerik': 'Hulu Perak', 'Pengkalan Hulu': 'Hulu Perak', 'Tapah': 'Batang Padang', 'Tanjong Malim': 'Muallim', 'Taiping': 'Larut dan Matang', 'Arau': 'Perlis', 'Kangar': 'Perlis', 'Padang Besar': 'Perlis', 'Ampang Jaya': 'Ulu Langat', 'Kajang': 'Ulu Langat', 'Klang Selatan': 'Klang', 'Klang Utara': 'Klang', 'Petaling Jaya': 'Petaling', 'Subang Jaya': 'Petaling', 'Shah Alam': 'Petaling', 'Sungai Buloh': 'Petaling', 'Petaling Perdana': 'Petaling', 'Petaling Utama': 'Petaling', 'Brickfields': 'Kuala Lumpur', 'Cheras': 'Kuala Lumpur', 'Dang Wangi': 'Kuala Lumpur', 'Sentul': 'Kuala Lumpur', 'Wangsa Maju': 'Kuala Lumpur', 'Kuala Muda': 'Kuala Muda/Yan', 'Yan': 'Kuala Muda/Yan', 'Kulim': 'Kulim/Bandar Baharu', 'Bandar Baharu': 'Kulim/Bandar Baharu', 'Jempol': 'Jempol/Jelebu', 'Jelebu': 'Jempol/Jelebu', 'Larut dan Matang': 'Larut/Matang/Selama', 'Selama': 'Larut/Matang/Selama', 'Telupid': 'Telupid/Tongod', 'Tongod': 'Telupid/Tongod', 'Tatau': 'Tatau/Sebauh', 'Sebauh': 'Tatau/Sebauh', 'Matu': 'Matu/Daro', 'Daro': 'Matu/Daro', ' Matu Daro': 'Matu/Daro', 'W.P. Kuala Lumpur': 'Kuala Lumpur', 'W.P. Labuan': 'Labuan', 'W.P. Putrajaya': 'Putrajaya'}

In [90]:
# 3. Apply mappings and aggregate overlapping rows
for name, df in dfs.items():
    # Strip whitespace to prevent missed matches
    df['state'] = df['state'].str.strip()
    df['district'] = df['district'].str.strip()
    
    # Elevate Putrajaya and Labuan out of any nested state (fixes the crime dataset)
    df.loc[df['district'].isin(['W.P. Putrajaya', 'Putrajaya']), 'state'] = 'Putrajaya'
    df.loc[df['district'].isin(['W.P. Labuan', 'Labuan']), 'state'] = 'Labuan'
    
    # Strip 'W.P. ' from all State and District labels
    df['state'] = df['state'].replace(wp_renames)
    
    # Standardize sub-districts, fine units, and spelling
    df['district'] = df['district'].replace(master_map)
    
    # Isolate non-numeric columns to keep them distinct in the groupby
    group_cols = [col for col in ['state', 'district', 'date', 'category', 'type', 'stage', 'sex', 'age', 'ethnicity'] if col in df.columns]
    
    # Group by the new standardized labels to collapse sub-units mathematically
    dfs[name] = df.groupby(group_cols, as_index=False).sum(numeric_only=True)

In [91]:
# 3. Apply mappings and aggregate overlapping rows
for name, df in dfs.items():
    # Strip whitespace to prevent missed matches
    df['state'] = df['state'].str.strip()
    df['district'] = df['district'].str.strip()
    
    # Elevate Putrajaya and Labuan out of any nested state (fixes the crime dataset)
    df.loc[df['district'].isin(['W.P. Putrajaya', 'Putrajaya']), 'state'] = 'Putrajaya'
    df.loc[df['district'].isin(['W.P. Labuan', 'Labuan']), 'state'] = 'Labuan'
    
    # Strip 'W.P. ' from all State and District labels
    df['state'] = df['state'].replace(wp_renames)
    
    # Standardize sub-districts, fine units, and spelling
    df['district'] = df['district'].replace(master_map)
    
    # Isolate non-numeric columns to keep them distinct in the groupby
    group_cols = [col for col in ['state', 'district', 'date', 'category', 'type', 'stage', 'sex', 'age', 'ethnicity'] if col in df.columns]
    
    # Group by the new standardized labels to collapse sub-units mathematically
    dfs[name] = df.groupby(group_cols, as_index=False).sum(numeric_only=True)

In [110]:
# Serves as reference for crime , schools, enrolment data to see if they are filled across the years
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Malaysia']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
All,,,,,,2016-2023,,
All Districts,,,,,,,2017-2025,2017-2025

In [111]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Johor']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Batu Pahat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Johor Bahru,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kluang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Tinggi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kulai,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Mersing,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Muar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pontian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Segamat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tangkak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [112]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kedah']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Baling,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Setar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Muda/Yan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kubang Pasu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kulim/Bandar Baharu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Langkawi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Padang Terap,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pendang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pokok Sena,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2022
Sik,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

### Since Pokok Sena is missing the crime data, it should be merged into its IPD, which is Kota Setar as of 29 Sep 2026

In [113]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kelantan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bachok,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Gua Musang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Jeli,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kecil Lojing,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Kota Bharu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Krai,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Machang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pasir Mas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pasir Puteh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tanah Merah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tumpat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

### Since Kecil Lojing is missing the crime data, it should be merged into its IPD, which is Gua Musang as of 29 Sep 2026

In [114]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Putrajaya']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Putrajaya,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,,,,2017-2025,2017-2025

In [115]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Kuala Lumpur']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Kuala Lumpur,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All,,,,,,2016-2023,,
All Districts,,,,,,,2017-2025,2017-2025

In [116]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Labuan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Labuan,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,,,,2017-2025,2017-2025

In [117]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Melaka']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Alor Gajah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Jasin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Melaka Tengah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [118]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Negeri Sembilan']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Jempol/Jelebu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Pilah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Port Dickson,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Rembau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Seremban,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tampin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [119]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Pahang']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bentong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bera,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Cameron Highlands,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Jerantut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuantan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lipis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Maran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pekan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Raub,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Rompin,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Temerloh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [120]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Perak']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Bagan Datuk,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Batang Padang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Hilir Perak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Hulu Perak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kampar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2018-2022
Kerian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kinta,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Kangsar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Larut/Matang/Selama,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Manjung,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Muallim,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2018-2025
Perak Tengah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

### Since Bagan Datuk is missing the crime data, it should be merged into its IPD, which is Hilir Perak as of 29 Sep 2026

In [121]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Perlis']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Perlis,2019-2022,2019-2022,2019-2022,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All,,,,,,2016-2023,,
All Districts,,,,,,,2017-2025,2017-2025

In [122]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Pulau Pinang']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Barat Daya,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Seberang Perai Selatan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Seberang Perai Tengah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Seberang Perai Utara,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Timur Laut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

In [123]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Sabah']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Beaufort,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Beluran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kalabakan,2022-2024,2022-2024,2022-2024,2016-2024,2020-2025,,,
Keningau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kinabatangan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Belud,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Kinabalu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kota Marudu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Penyu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kudat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kunak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lahad Datu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Membakut,2024-2024,2024-2024,2024-2024,,,,,
Nabawan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Papar,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Penampang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pitas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Putatan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Ranau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sandakan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Semporna,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sipitang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tambunan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Tawau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Telupid/Tongod,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Tenom,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tuaran,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

### Since several districts are missing the crime data, they should be merged into its IPD as of 29 Sep 2026
- Kalabakan : Tawau
- Kuala Penyu, Membakut : Beaufort
- Nabawan, Tambunan : Keningau
- Pitas : Kota Marudu
- Putatan : Penampang
- Telupid/Tongod : Beluran

In [106]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Sarawak']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Asajaya,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Bau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Belaga,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Beluru,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Betong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bintulu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Bukit Mabong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Dalat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Gedong,2024-2024,2024-2024,2024-2024,,,,,
Julau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kabong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Kanowit,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kapit,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuching,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lawas,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Limbang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lingga,2024-2024,2024-2024,2024-2024,,,,,
Lubok Antu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Lundu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Maradong,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Marudi,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2022
Matu/Daro,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Miri,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Mukah,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Pakan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Pantu,2024-2024,2024-2024,2024-2024,,,,,
Pusa,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2018-2022
Samarahan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Saratok,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sarikei,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sebuyau,2024-2024,2024-2024,2024-2024,,,,,
Selangau,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2022,2017-2025
Serian,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sibu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Siburan,2024-2024,2024-2024,2024-2024,,,,,
Simunjan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Song,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sri Aman,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Subis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Tanjung Manis,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Tatau/Sebauh,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Tebedu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
Telang Usan,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,,
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Matu Daro,,,,,,2016-2023,,
Padawan,,,,,,2016-2023,,2023-2025
Baram,,,,,,,,2023-2025

### Since several districts are missing the crime data, they should be merged into its IPD as of 29 Sep 2026
- Asajaya : Kota Samarahan
- Beluru : Marudi
- Bukit Mabong : Kapit
- Gedong : Simunjan
- Kabong : Saratok
- Lingga : Sri Aman
- Matu/Daro : Daro (Matu Daro in the table)
- Pakan : Julau
- Pantu : Sri Aman
- Pusa : Saratok
- Sebuyau : Sri Aman
- Selangau : Mukah
- Siburan : Padawan
- Subis : Miri
- Tanjung Manis : Sarikei
- Tebedu : Serian
- Telang Usan : Marudi
- Baram : Marudi

In [124]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Selangor']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Gombak,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Klang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Langat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Selangor,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Petaling,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sabak Bernam,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Sepang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Ulu Langat,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Ulu Selangor,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,
Serdang,,,,,,2016-2023,,

### Serdang is its own police district but is under Petaling district administratively

In [125]:
cols = []
for name, d in dfs.items():
    g = d.assign(year=d['date'].str[:4]).groupby(['state', 'district'])['year'].agg(['min', 'max'])
    cols.append((g['min'] + '-' + g['max']).rename(name))

yrs_w_data = pd.concat(cols, axis=1).fillna('')
yrs_w_data.loc['Terengganu']

,income,poverty,inequality,amenities,population,crime,schools,enrolment
district,,,,,,,,
Besut,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Dungun,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Hulu Terengganu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kemaman,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Kuala Nerus,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,,2017-2025,2017-2025
Kuala Terengganu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Marang,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
Setiu,2019-2024,2019-2024,2019-2024,2016-2024,2020-2025,2016-2023,2017-2025,2017-2025
All Districts,,,,2016-2024,,,2017-2025,2017-2025
All,,,,,,2016-2023,,

### Since Kuala Nerus is missing the crime data, it should be merged into its IPD, which is Kuala Terengganu as of 29 Sep 2026

In [ ]:
# concat['state'].unique()

In [ ]:
# df_dropped = concat[(concat['district'] != 'All') & (concat['district'] != 'All Districts')]

In [ ]:
# df_dropped.info()

In [ ]:
# df_dropped = df_dropped[(df_dropped['state'] != 'Malaysia')]

In [ ]:
# df_dropped.head()

In [ ]:
# df_dropped.to_csv('dropped.csv', index=False)